version: '3.5'

services:
  jupyter:
    build:
      context: .
      args:
        JUPYTER_USER: ${JUPYTER_USER}  # from .env file
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - "${HOME}:/work"
